name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      host: ${{ secrets.AWS_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -la ~/.ssh
          echo "Key file created and permissions set"
          

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Current user: $(whoami)"
            echo "Current directory: $(pwd)"
            
            # Check if repository exists
            if [ ! -d "fastapi-book-project" ]; then
              git clone https://github.com/FFTCMJBJ054/fastapi-book-project.git
            fi
            
            cd fastapi-book-project

            git stash
            git pull origin main

            # Stop existing containers
            docker-compose down || true
            
            # Build and start containers
            docker-compose up --build -d
            
            # Verify containers are running
            docker ps 

            
          