name: Continuous Integration Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "requirements.txt not found!"
            exit 1
          fi

      - name: Run tests
        run: pytest

      - name: Test Docker Build
        run: |
          docker build -t fastapi-app .
          docker run -d --name test-fastapi -p 8000:8000 fastapi-app
          sleep 5

      - name: Check Docker Logs
        run: |
          docker ps -a
          docker logs test-fastapi

      - name: Test API Endpoint
        run: |
          curl -f http://localhost:8000/api/v1/books || (echo "API test failed!" && exit 1)